newnew-8529c3b_custom-prod_app_05db4fd_env_99a473c.yaml Updated

diff --git a/.github/workflows/newnew-8529c3b_custom-prod_app_05db4fd_env_99a473c.yaml b/.github/workflows/newnew-8529c3b_custom-prod_app_05db4fd_env_99a473c.yaml
--- a/.github/workflows/newnew-8529c3b_custom-prod_app_05db4fd_env_99a473c.yaml
+++ b/.github/workflows/newnew-8529c3b_custom-prod_app_05db4fd_env_99a473c.yaml
@@ -10,7 +10,7 @@ name: newnew-8529c3b_custom-prod_app_05db4fd_env_99a473c Pipeline (Skyu Generate
       - README.md
   workflow_dispatch: {}
   repository_dispatch:
-    types: pipeline_77afade4-8403-4ff4-98ab-1685aed4c757
+    types: pipeline_b547a5be-4372-4063-b83a-8ad5d600b0f4
 env:
   ENCODED_PIPELINE_SECRET: ${{secrets.ENVAPP_NEWNEW8529C3B_CUSTOMPROD_APP_05DB4FD_ENV_99A473C}}
   COMMIT_ID: ${{github.event.client_payload.commitId || github.sha || github.run_id}}
@@ -71,7 +71,7 @@ jobs:
       - name: 'Run :: Trivy Filesystem Scan'
         run: |2-
 
-                  docker run --rm -v "${PWD}:/src" aquasec/trivy fs /src --format json --quiet > trivy_results.json
+                  docker run --rm -v "${PWD}:/src" aquasec/trivy:0.69.3 fs /src --format json --quiet > trivy_results.json
                   # Minifying Json
                   jq -c '.' trivy_results.json > trivy_results.min.json
                   
@@ -146,9 +146,11 @@ jobs:
       - name: 'Run :: Trivy Filesystem Scan (Including Trivy Ignores)'
         run: |2-
 
-                  docker run --rm -v "${PWD}:/src" aquasec/trivy fs /src --format json --quiet --report summary --dependency-tree > trivy_results.json
+                  docker run --rm -v "${PWD}:/src" aquasec/trivy:0.69.3 fs /src --format json --quiet --report summary --dependency-tree > trivy_results.json
                   # Minifying Json
                   jq -c '.' trivy_results.json > trivy_results.min.json
+                  # Generating SBOM in CycloneDX format
+                  docker run --rm -v "${PWD}:/src" aquasec/trivy:0.69.3 fs /src --format cyclonedx --output /src/sbom.json
                   
       - name: 'Run :: Upload Code Scan Reports'
         env:
@@ -194,6 +196,16 @@ jobs:
                   echo "Uploading Trivy Ignore File" 
                   if [ -f ".trivyignore" ]; then
                     response=$(curl -X POST -F 'file=@.trivyignore' -F 'provider=aws' -F 'resourceType=trivy-ignore' -F 'cloudStoragePath=/${{ env.PIPELINE_APPLICATION_ID }}/trivy-ignore-file/${{ env.COMMIT_ID }}/' -F 'pipelineRunId=${{ env.RUN_ID }}'  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-environment-id: ${{ env.PIPELINE_ENVIRONMENT_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-resource-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'x-auth-by: sa' -H 'Content-Type: multipart/form-data'  "${{ env.S3_UPLOAD_ENDPOINT }}")
+
+                    if echo "$response" | grep -q '"success":true'; then
+                      echo "SUCCESS :: $response"
+                    else
+                      echo "FAILED :: $response"
+                    fi
+
+                  echo "Uploading SBOM File" 
+                  if [ -f "sbom.json" ]; then
+                    response=$(curl -X POST -F 'file=@sbom.json' -F 'provider=aws' -F 'resourceType=sbom' -F 'cloudStoragePath=/${{ env.PIPELINE_APPLICATION_ID }}/sbom-file/${{ env.COMMIT_ID }}/' -F 'pipelineRunId=${{ env.RUN_ID }}'  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-environment-id: ${{ env.PIPELINE_ENVIRONMENT_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-resource-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'x-auth-by: sa' -H 'Content-Type: multipart/form-data'  "${{ env.S3_UPLOAD_ENDPOINT }}")
 
                     if echo "$response" | grep -q '"success":true'; then
                       echo "SUCCESS :: $response"
@@ -521,6 +533,100 @@ jobs:
       - _status_testing
     permissions: write-all
     runs-on: ubuntu-latest
+  deploy:
+    name: deploy
+    steps:
+      - name: 'Run :: Start'
+        run: |2-
+
+              echo " Starting GitHub Action!" && 
+              echo "STEPS_CAN_PROCEED=true" >> $GITHUB_ENV
+              
+      - name: 'Run :: Decoding Secrets'
+        run: |2-
+
+                if [ ! -x "$(command -v jq)" ]; then
+                  echo "jq not found, installing..."
+                  sudo apt-get update
+                  sudo apt-get install -y jq
+                fi
+                echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
+                
+      - name: 'Run :: Checkout repository'
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - name: 'Run :: Checkout Specific Commit'
+        env:
+          COMMIT_ID: ${{ github.event.client_payload.commitId }}
+          BRANCH_NAME: ${{ github.event.client_payload.branchName }}
+        if: >-
+          ${{ github.event.client_payload.commitId != null ||
+          github.event.client_payload.branchName != null }}
+        run: |2-
+
+              echo "Starting the checkout process..."
+              git fetch --all
+              if [ -n "$COMMIT_ID" ]; then
+                echo "Commit ID provided: $COMMIT_ID"
+                git checkout $COMMIT_ID || true
+                echo "Checked out to commit ID: $COMMIT_ID"
+              elif [ -n "$BRANCH_NAME" ]; then
+                echo "Branch name provided: $BRANCH_NAME"
+                git checkout $BRANCH_NAME || true
+                echo "Checked out to branch: $BRANCH_NAME"
+
+                #Updating the commit Id
+                ACTUAL_COMMIT_ID=$(git rev-parse HEAD)
+                echo "Changing CommitId: $ACTUAL_COMMIT_ID"
+                echo "COMMIT_ID=$ACTUAL_COMMIT_ID" >> $GITHUB_ENV
+              else
+                echo "Skipping checkout..."
+              fi
+            
+      - name: 'Run :: Deploy and Notify Resource Service'
+        env:
+          RUN_ID: ${{ github.run_id }}
+          COMMIT_USER: ${{ github.event.head_commit.author.name }}
+          COMMIT_TIME: ${{ github.event.head_commit.timestamp }}
+          COMMIT_MESSAGE: >-
+            ${{ github.event.head_commit.message ||
+            github.event.client_payload.commitMessage }}
+        run: >2-
+
+              if [ -z "$COMMIT_MESSAGE" ]; then
+                COMMIT_MESSAGE=$(git log -1 --pretty=%B)
+              fi
+              # Sanitize commit message: remove newlines, replace &, trim spaces
+              COMMIT_MESSAGE=$(echo "$COMMIT_MESSAGE"       | tr '
+          ' ' '       | sed 's/&/and/g'       | sed
+          's/^[[:space:]]*//;s/[[:space:]]*$//')
+
+              echo "Sanitized commit message: $COMMIT_MESSAGE"
+              echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
+            
+              response=$(curl -X PATCH -d "imageRegistryURL=${{ env.IMAGE_NAME }}&appVersionId=${{ env.DEPLOYMENT_APP_VERSION_ID }}&tag=${{ env.COMMIT_ID }}&containerName=${{ env.DEPLOYMENT_CONTAINER_NAME }}&shouldDeploy=${{env.DEPLOY_STEP_SHOULD_DEPLOY}}&pipelineRunId=${{ env.RUN_ID }}&commitDetails[commitHash]=${{ env.COMMIT_ID }}&commitDetails[commitAvatar]=https://github.com/$COMMIT_USER.png&commitDetails[commitTime]=$COMMIT_TIME&commitDetails[commitMessage]=$COMMIT_MESSAGE&commitDetails[commitUser]=$COMMIT_USER"  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-environment-id: ${{ env.PIPELINE_ENVIRONMENT_ID }}' -H 'x-application-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-resource-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'x-auth-by: sa' -H 'Content-Type: application/x-www-form-urlencoded'  "${{ env.DEPLOYMENT_ENDPOINT }}")
+              
+              status_code=$?
+
+              if [ $status_code -eq 0 ]; then
+                if echo "$response" | grep -q '"success":true'; then
+                  echo "SUCCESS :: $response"
+                else
+                  echo "FAILED :: $response"
+                  exit 1
+                fi
+              else
+                echo "Failed to deploy. HTTP status code: $status_code"
+                exit 1
+              fi
+            
+    needs:
+      - custom-job
+      - _status_testing
+    permissions: write-all
+    if: github.event.client_payload.releaseData == null
+    runs-on: ubuntu-latest
   _status-success:
     name: _status-success
     steps:
@@ -679,97 +785,4 @@ jobs:
     if: ${{ failure() || cancelled() }}
     env:
       CONTEXT_JSON: ${{ toJson(github) }}
-    runs-on: ubuntu-latest
-  deploy:
-    name: deploy
-    steps:
-      - name: 'Run :: Start'
-        run: |2-
-
-              echo " Starting GitHub Action!" && 
-              echo "STEPS_CAN_PROCEED=true" >> $GITHUB_ENV
-              
-      - name: 'Run :: Decoding Secrets'
-        run: |2-
-
-                if [ ! -x "$(command -v jq)" ]; then
-                  echo "jq not found, installing..."
-                  sudo apt-get update
-                  sudo apt-get install -y jq
-                fi
-                echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
-                
-      - name: 'Run :: Checkout repository'
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: 'Run :: Checkout Specific Commit'
-        env:
-          COMMIT_ID: ${{ github.event.client_payload.commitId }}
-          BRANCH_NAME: ${{ github.event.client_payload.branchName }}
-        if: >-
-          ${{ github.event.client_payload.commitId != null ||
-          github.event.client_payload.branchName != null }}
-        run: |2-
-
-              echo "Starting the checkout process..."
-              git fetch --all
-              if [ -n "$COMMIT_ID" ]; then
-                echo "Commit ID provided: $COMMIT_ID"
-                git checkout $COMMIT_ID || true
-                echo "Checked out to commit ID: $COMMIT_ID"
-              elif [ -n "$BRANCH_NAME" ]; then
-                echo "Branch name provided: $BRANCH_NAME"
-                git checkout $BRANCH_NAME || true
-                echo "Checked out to branch: $BRANCH_NAME"
-
-                #Updating the commit Id
-                ACTUAL_COMMIT_ID=$(git rev-parse HEAD)
-                echo "Changing CommitId: $ACTUAL_COMMIT_ID"
-                echo "COMMIT_ID=$ACTUAL_COMMIT_ID" >> $GITHUB_ENV
-              else
-                echo "Skipping checkout..."
-              fi
-            
-      - name: 'Run :: Deploy and Notify Resource Service'
-        env:
-          RUN_ID: ${{ github.run_id }}
-          COMMIT_USER: ${{ github.event.head_commit.author.name }}
-          COMMIT_TIME: ${{ github.event.head_commit.timestamp }}
-          COMMIT_MESSAGE: >-
-            ${{ github.event.head_commit.message ||
-            github.event.client_payload.commitMessage }}
-        run: >2-
-
-              if [ -z "$COMMIT_MESSAGE" ]; then
-                COMMIT_MESSAGE=$(git log -1 --pretty=%B)
-              fi
-              # Sanitize commit message: remove newlines, replace &, trim spaces
-              COMMIT_MESSAGE=$(echo "$COMMIT_MESSAGE"       | tr '
-          ' ' '       | sed 's/&/and/g'       | sed
-          's/^[[:space:]]*//;s/[[:space:]]*$//')
-
-              echo "Sanitized commit message: $COMMIT_MESSAGE"
-              echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
-            
-              response=$(curl -X PATCH -d "imageRegistryURL=${{ env.IMAGE_NAME }}&appVersionId=${{ env.DEPLOYMENT_APP_VERSION_ID }}&tag=${{ env.COMMIT_ID }}&containerName=${{ env.DEPLOYMENT_CONTAINER_NAME }}&shouldDeploy=${{env.DEPLOY_STEP_SHOULD_DEPLOY}}&pipelineRunId=${{ env.RUN_ID }}&commitDetails[commitHash]=${{ env.COMMIT_ID }}&commitDetails[commitAvatar]=https://github.com/$COMMIT_USER.png&commitDetails[commitTime]=$COMMIT_TIME&commitDetails[commitMessage]=$COMMIT_MESSAGE&commitDetails[commitUser]=$COMMIT_USER"  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-environment-id: ${{ env.PIPELINE_ENVIRONMENT_ID }}' -H 'x-application-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-resource-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'x-auth-by: sa' -H 'Content-Type: application/x-www-form-urlencoded'  "${{ env.DEPLOYMENT_ENDPOINT }}")
-              
-              status_code=$?
-
-              if [ $status_code -eq 0 ]; then
-                if echo "$response" | grep -q '"success":true'; then
-                  echo "SUCCESS :: $response"
-                else
-                  echo "FAILED :: $response"
-                  exit 1
-                fi
-              else
-                echo "Failed to deploy. HTTP status code: $status_code"
-                exit 1
-              fi
-            
-    needs:
-      - custom-job
-    permissions: write-all
-    if: github.event.client_payload.releaseData == null
     runs-on: ubuntu-latest
